web:
  build: ./app
  volumes:
    - /usr/share/nginx/html
  ports:
    - "3000"
  command: node ./bin/www

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - web
  links:
    - web:web
