# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Casey Dunham

# Copy custom configuration file from the current directory
COPY sites-available/default /etc/nginx/sites-available/default
